polls/poll/urls.py
from django.urls import path

from . import views

app_name = 'poll'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),                          # https://sitename/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),               # https://sitename/question_id/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),     # https://sitename/question_id/results/
    path('<int:question_id>/vote/', views.vote, name='vote'),                   # https://sitename/question_id/vote/
]

polls/polls/urls.py
from django.contrib import admin
from django.urls import path, include

from poll import views

urlpatterns = [
    path('', include('poll.urls')),                         # https://sitename/...
    path('admin/', admin.site.urls),                        # https://sitename/admin/
]

polls/poll/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering='pub_date',
    )
    def was_published_recently(self):
        """ Returns True if the question was published
            within a time period of 1 day"""
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/poll/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import *


class IndexView(generic.ListView):
    template_name = 'poll/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """ Return the latest 5 questions (does not take into questions with "pub_date" set to future """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'poll/detail.html'

    def get_queryset(self):
        """ Return only questions with "pub_date" not set to future """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'poll/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):

        return render(request, 'poll/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('poll:results', args=(question.id,)))

polls/poll/templates/poll/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en", class="h-100">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>

    <link rel="stylesheet" href="{% static 'poll/css/main.css' %}">

    <title>{{ title }}</title>
</head>

<body class="d-flex h-100 text-center text-white bg-dark">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column" style="font-size: 20px;">
        <br />
        <br />
        <header class="mb-auto">

        </header>

        <main class="px-3">
            {% block content %}{% endblock %}
        </main>

        <footer class="mt-auto text-white-50" style="font-size: 16px;">
            <br />
            <br />
            <br />
            <p>Made by <a href="https://github.com/neverFeltAlive" class="link-secondary">neverFeltAlive</a>.</p>
        </footer>
        <br />
        <br />

    </div>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>

polls/poll/templates/poll/detail.html
{% extends 'poll/base.html' %}

{% block content %}
<form action="{% url 'poll:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>{{ question.question_text }}</h1>
        </legend>
        <br />
        <hr />
        <br />
        <div class="form-check" style="text-align: left;">
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
            <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}"
                value="{{ choice.id }}">
            <label class="form-check-label" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
            <br />
            <br />
            {% endfor %}
        </div>
    </fieldset>
    <br />
    <hr />
    <br />
    <input type="submit" value="Vote" class="btn btn-secondary" style="color: white;">
</form>
{% endblock %}

polls/poll/templates/poll/index.html
{% extends 'poll/base.html' %}

{% block content %}
<div>
    {% if latest_question_list %}
    <h1>Available polls:</h1>
    <br />
    <hr />
    <div>
        <nav class="nav nav-masthead justify-content-center">
            {% for question in latest_question_list %}
            <a class="nav-link" href="{% url 'poll:detail' question.id %}">{{ question.question_text }}</a>    
            {% endfor %}
        </nav>
    </div>
    <hr />
    {% else %}
    <h1>No polls are available.</h1>
    {% endif %}
</div>
{% endblock %}

polls/poll/templates/poll/results.html
{% extends 'poll/base.html' %}

{% block content %}
<h1>{{ question.question_text }}</h1>
<br />
<hr />
<br />
<ul style="text-align: left;">
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- <b>{{ choice.votes }} vote{{ choice.votes|pluralize }}</b></li>
    {% endfor %}
</ul>
<br />
<hr />
<br />
<a href="{% url 'poll:index' %}" class="btn btn-secondary" style="color: white;">Home</a>
{% endblock %}